name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test (H2 in-memory)
        working-directory: backend/utpmarket
        run: mvn clean test package -B -Dspring.profiles.active=test

      - name: Generate dependency graph
        working-directory: backend/utpmarket
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph

  deploy:
    name: Deploy to Azure (optional)
    runs-on: ubuntu-latest
    needs: build-test
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run for Azure
        working-directory: backend/utpmarket
        run: mvn clean package spring-boot:run -B -Dspring.profiles.active=prod
