name: Java CI/CD with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test (H2 in-memory)
        working-directory: backend/utpmarket
        run: mvn clean test package -B -Dspring.profiles.active=test

      - name: Generate dependency graph
        working-directory: backend/utpmarket
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
