name: React Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/UTP-Market/package-lock.json

    - name: Install dependencies
      working-directory: frontend/UTP-Market
      run: npm ci

    - name: Build React app
      working-directory: frontend/UTP-Market
      run: npm run build --if-present

    - name: Run tests
      working-directory: frontend/UTP-Market
      run: npm test
